#! /bin/make -f

PROJECT := ChordPro

.PHONY : build
build : version
	cavaconsole --scan --build --makeins --project=.

.PHONY : build_noscan
build_noscan : version
	cavaconsole --build --makeins --project=.

clean :
	rm -r release/${PROJECT}
	rm installer/*

.PHONY : version
version :
	perl setversion.pl
