#! /bin/make -f

.PHONY : chordpro wxchordpro

chordpro :
	pp --output=chordpro @chordpro.pp ../script/chordpro-script.pl

wxchordpro :
	pp --output=wxchordpro @chordpro.pp @wxchordpro.pp ../script/wxchordpro.pl
