#! /bin/make -f

.PHONY : chordpro wxchordpro

# Use pp from path, not necessarily /usr/bin.
PP := perl -S pp

chordpro : res
	${PP} --output=chordpro @chordpro.pp ../script/chordpro.pl

wxchordpro : res
	${PP} --output=wxchordpro @wxchordpro.pp ../script/wxchordpro.pl

res :
	: test -f ../Makefile && make -C .. -f Makefile resources

clean ::
	rm -f *.pp.deps *~ chordpro wxchordpro
