name: Full Build on MacOS

on: push

jobs:
  macOS-full:
    runs-on: macOS-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: perl -V
        run: perl -V
      - name: Install cpanm
        run: brew install cpanm
      - name: Install H::B
        continue-on-error: true
        run: cpanm HarfBuzz::Shaper
      - name: Oops
        continue-on-error: true
        run: cat /Users/runner/.cpanm/build.log
      - name: Install Dependencies
        run: |
          perl -ni~ -e 'print unless /HarfBuzz/' Makefile.PL
          cpanm --installdeps --notest .
      - name: Run Tests
        run: prove -l t
      - name: Set up wxWidgets
        run: brew install wxwidgets@3.2
      - name: Install Dependencies
        run: |
          cpanm Net::SSLeay --notest
      - name: Install Alien;;wxWidgets
        run: |
          cpanm https://github.com/sciurius/perl-Alien-wxWidgets/releases/download/R0.71/Alien-wxWidgets-0.71.tar.gz
          perl -MAlien::wxWidgets -e 'Alien::wxWidgets->libraries(qw(stc media webview propgrid ribbon aui xrc qa html))'
      - name: Install wxPerl
        run: |
          cpanm https://github.com/sciurius/wxPerl/releases/download/R3.005/Wx-3.005.tar.gz --notest
      - name: Build DMG
        run: |
          find / -type f \( -name libpng\*.dylib \) -o \( -name libjpeg\*.dylib \) -o \( -name libtiff\*.dylib \) -o \( -name libz\*.dylib \) -o \( -name liblzma\*.dylib \) -o \( -name libzstd\*.dylib \) -o \( -name libpcre2\*.dylib \) -print
          make -C pp/macos
