name: CI for Microsoft Windows

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perl:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Perl
        run: |
          choco install strawberryperl
          echo "C:\strawberry\perl\bin" >> $GITHUB_PATH
          echo "C:\strawberry\c\bin;C:\strawberry\perl\site\bin" >> $GITHUB_PATH
      - name: perl -V
        run: perl -V
      - name: Install Dependencies
        run: cpanm --installdeps --notest .
      - name: Make and run tests
        run: |
            perl Makefile.PL
            gmake
            gmake test
