name: CI for Microsoft Windows

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perl:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Strawberry Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
            distribution: strawberry
      - name: perl -V
        run: perl -V
      - name: Install Dependencies
        run: cpanm --installdeps --notest .
      - name: Make and run tests
        - run: cpanm HarfBuzz::Shaper
        - run: perl Makefile.PL
        - run: gmake
        - run: gmake test
