name: CI for Microsoft Windows

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perl:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: shogo82148/actions-setup-perl@v1
        with:
            distribution: strawberry
      - name: perl -V
        run: perl -V
      - name: Install Optional Dependencies
        run: cpanm HarfBuzz::Shaper
      - name: Install Dependencies
        run: cpanm --installdeps --notest .
      - name: Make and run tests
        run: |
            perl Makefile.PL
            gmake
            gmake test
