# generated by wxGlade 1.1.0b1 on Fri Oct  4 15:07:28 2024
#
# To get wxPerl visit http://www.wxperl.it
#

use Wx qw[:allclasses];
use strict;

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade

package ChordPro::Wx::EditorPanel_wxg;

use Wx qw[:everything];
use base qw(Wx::Panel);
use strict;

sub new {
    my( $self, $parent, $id, $pos, $size, $style, $name ) = @_;
    $parent //= undef;
    $id     //= -1;
    $pos    //= wxDefaultPosition;
    $size   //= wxDefaultSize;
    $name   //= "";

    # begin wxGlade: ChordPro::Wx::EditorPanel_wxg::new
    use ChordPro::Wx::Utils;
    $style = wxTAB_TRAVERSAL
        unless defined $style;

    $self = $self->SUPER::new( $parent, $id, $pos, $size, $style, $name );
    
    $self->{sz_main} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{sw_main} = Wx::SplitterWindow->new($self, wxID_ANY);
    $self->{sz_main}->Add($self->{sw_main}, 1, wxEXPAND, 0);
    
    $self->{p_left} = Wx::Panel->new($self->{sw_main}, wxID_ANY);
    
    $self->{sz_source} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{p_left}, wxID_ANY, "Song source"), wxVERTICAL);
    
    $self->{t_source} = Wx::TextCtrl->new($self->{sz_source}->GetStaticBox(), wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE);
    $self->{t_source}->SetFocus();
    $self->{sz_source}->Add($self->{t_source}, 1, wxEXPAND, 0);
    
    $self->{sizer_2} = Wx::FlexGridSizer->new(1, 4, 0, 5);
    $self->{sz_source}->Add($self->{sizer_2}, 0, wxEXPAND|wxTOP, 5);
    
    $self->{l_status} = Wx::StaticText->new($self->{sz_source}->GetStaticBox(), wxID_ANY, "Status");
    $self->{sizer_2}->Add($self->{l_status}, 1, wxALIGN_CENTER_VERTICAL|wxEXPAND, 0);
    
    $self->{b_prefs} = Wx::Button->new($self->{sz_source}->GetStaticBox(), wxID_PREFERENCES, "");
    $self->{sizer_2}->Add($self->{b_prefs}, 0, 0, 0);
    
    $self->{b_preview} = Wx::Button->new($self->{sz_source}->GetStaticBox(), wxID_ANY, "Preview");
    $self->{sizer_2}->Add($self->{b_preview}, 0, 0, 5);
    
    $self->{b_msgs} = Wx::Button->new($self->{sz_source}->GetStaticBox(), wxID_ANY, "Show Messages");
    $self->{sizer_2}->Add($self->{b_msgs}, 0, 0, 5);
    
    $self->{p_preview} = Wx::Panel->new($self->{sw_main}, wxID_ANY);
    
    $self->{sz_prv} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{p_preview}, wxID_ANY, "Preview"), wxVERTICAL);
    
    $self->{webview} = Wx::WebView::New($self->{sz_prv}->GetStaticBox(), wxID_ANY, $self->{defaulturl});
    $self->{sz_prv}->Add($self->{webview}, 1, wxEXPAND, 0);
    
    $self->{sizer_1} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{sz_prv}->Add($self->{sizer_1}, 0, wxEXPAND|wxTOP, 5);
    
    $self->{sizer_1}->Add(1, 1, 1, wxEXPAND, 0);
    
    $self->{button_1} = Wx::Button->new($self->{sz_prv}->GetStaticBox(), wxID_SAVE, "");
    $self->{sizer_1}->Add($self->{button_1}, 0, wxRIGHT, 5);
    
    $self->{button_2} = Wx::Button->new($self->{sz_prv}->GetStaticBox(), wxID_CLOSE, "");
    $self->{sizer_1}->Add($self->{button_2}, 0, 0, 0);
    
    $self->{p_preview}->SetSizer($self->{sz_prv});
    
    $self->{sizer_2}->AddGrowableCol(0);
    
    $self->{p_left}->SetSizer($self->{sz_source});
    
    $self->{sw_main}->SplitVertically($self->{p_left}, $self->{p_preview}, , -1);
    
    $self->SetSizer($self->{sz_main});
    $self->{sz_main}->Fit($self);
    
    $self->Layout();
    Wx::Event::EVT_TEXT($self, $self->{t_source}->GetId, $self->can('OnText'));
    Wx::Event::EVT_BUTTON($self, $self->{b_prefs}->GetId, $self->can('OnPreferences'));
    Wx::Event::EVT_BUTTON($self, $self->{b_preview}->GetId, $self->can('OnPreview'));
    Wx::Event::EVT_BUTTON($self, $self->{b_msgs}->GetId, $self->can('OnShowMessages'));
    Wx::Event::EVT_BUTTON($self, $self->{button_1}->GetId, $self->can('OnPreviewSave'));
    Wx::Event::EVT_BUTTON($self, $self->{button_2}->GetId, $self->can('OnPreviewClose'));

    # end wxGlade
    return $self;

}


sub OnText {
    my ($self, $event) = @_;
    # wxGlade: ChordPro::Wx::EditorPanel_wxg::OnText <event_handler>
    warn "Event handler (OnText) not implemented";
    $event->Skip;
    # end wxGlade
}


sub OnPreferences {
    my ($self, $event) = @_;
    # wxGlade: ChordPro::Wx::EditorPanel_wxg::OnPreferences <event_handler>
    warn "Event handler (OnPreferences) not implemented";
    $event->Skip;
    # end wxGlade
}


sub OnPreview {
    my ($self, $event) = @_;
    # wxGlade: ChordPro::Wx::EditorPanel_wxg::OnPreview <event_handler>
    warn "Event handler (OnPreview) not implemented";
    $event->Skip;
    # end wxGlade
}


sub OnShowMessages {
    my ($self, $event) = @_;
    # wxGlade: ChordPro::Wx::EditorPanel_wxg::OnShowMessages <event_handler>
    warn "Event handler (OnShowMessages) not implemented";
    $event->Skip;
    # end wxGlade
}


sub OnPreviewSave {
    my ($self, $event) = @_;
    # wxGlade: ChordPro::Wx::EditorPanel_wxg::OnPreviewSave <event_handler>
    warn "Event handler (OnPreviewSave) not implemented";
    $event->Skip;
    # end wxGlade
}


sub OnPreviewClose {
    my ($self, $event) = @_;
    # wxGlade: ChordPro::Wx::EditorPanel_wxg::OnPreviewClose <event_handler>
    warn "Event handler (OnPreviewClose) not implemented";
    $event->Skip;
    # end wxGlade
}


# end of class ChordPro::Wx::EditorPanel_wxg

1;

