# generated by wxGlade 1.1.0b1 on Fri Sep 13 13:32:53 2024
#
# To get wxPerl visit http://www.wxperl.it
#

use Wx qw[:allclasses];
use strict;
# begin wxGlade: dependencies
use Wx::Locale gettext => '_T';
# end wxGlade

# begin wxGlade: extracode
# end wxGlade

package ChordPro::Wx::MenuBar;

use Wx qw[:everything];
use base qw(Wx::MenuBar);
use strict;

# begin wxGlade: dependencies
use Wx::Locale gettext => '_T';
# end wxGlade

sub new {
    my( $self,  ) = @_;
    # begin wxGlade: ChordPro::Wx::MenuBar::new
    $self = $self->SUPER::new( @_[1 .. $#_] );
    my $wxglade_tmp_menu;
    $wxglade_tmp_menu = Wx::Menu->new();
    $wxglade_tmp_menu->Append(wxID_EXIT, _T("Exit\tCtrl-Q"), "");
    $self->Append($wxglade_tmp_menu, _T("&File"));
    Wx::Event::EVT_MENU($self, wxID_EXIT, $self->can('OnQuit'));

    # end wxGlade
    return $self;

}


sub OnQuit {
    my ($self, $event) = @_;
    # wxGlade: ChordPro::Wx::MenuBar::OnQuit <event_handler>
    warn "Event handler (OnQuit) not implemented";
    $event->Skip;
    # end wxGlade
}


# end of class ChordPro::Wx::MenuBar

1;

