# generated by wxGlade 1.1.0b1 on Thu Sep 12 22:44:10 2024
#
# To get wxPerl visit http://www.wxperl.it
#

use Wx qw[:allclasses];
use strict;

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade

package ChordPro::Wx::SongbookExportPanel_wxg;

use Wx qw[:everything];
use base qw(Wx::Panel);
use strict;

use Wx::Locale gettext => '_T';
sub new {
    my( $self, $parent, $id, $pos, $size, $style, $name ) = @_;
    $parent = undef              unless defined $parent;
    $id     = -1                 unless defined $id;
    $pos    = wxDefaultPosition  unless defined $pos;
    $size   = wxDefaultSize      unless defined $size;
    $name   = ""                 unless defined $name;

    # begin wxGlade: ChordPro::Wx::SongbookExportPanel_wxg::new
    use ChordPro::Wx::Utils;
    $self = $self->SUPER::new( $parent, $id, $pos, $size, $style, $name );
    
    $self->{sz_export_outer} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self, wxID_ANY, _T("Songbook Folder Export")), wxVERTICAL);
    
    $self->{sz_export_inner} = Wx::BoxSizer->new(wxVERTICAL);
    $self->{sz_export_outer}->Add($self->{sz_export_inner}, 0, wxEXPAND, 5);
    
    $self->{sizer_1} = Wx::BoxSizer->new(wxVERTICAL);
    $self->{sz_export_inner}->Add($self->{sizer_1}, 1, wxEXPAND, 0);
    
    $self->{sz_sbexp} = Wx::FlexGridSizer->new(6, 2, 5, 5);
    $self->{sizer_1}->Add($self->{sz_sbexp}, 0, wxEXPAND, 5);
    
    $self->{label_1} = Wx::StaticText->new($self->{sz_export_outer}->GetStaticBox(), wxID_ANY, _T("Folder"));
    $self->{sz_sbexp}->Add($self->{label_1}, 0, wxALIGN_CENTER_VERTICAL, 5);
    
    $self->{dp_folder} = Wx::DirPickerCtrl->new($self->{sz_export_outer}->GetStaticBox(), wxID_ANY, "", _T("Select folder"), wxDefaultPosition, wxDefaultSize, wxDIRP_SMALL|wxDIRP_USE_TEXTCTRL);
    $self->{sz_sbexp}->Add($self->{dp_folder}, 0, wxEXPAND, 0);
    
    $self->{sz_sbexp}->Add(1, 1, 0, 0, 0);
    
    $self->{l_info} = Wx::StaticText->new($self->{sz_export_outer}->GetStaticBox(), wxID_ANY, _T("Select a folder with ChordPro songs"));
    $self->{sz_sbexp}->Add($self->{l_info}, 0, wxALIGN_CENTER_VERTICAL|wxEXPAND, 0);
    
    $self->{sz_sbexp}->Add(1, 1, 0, 0, 0);
    
    $self->{sz_sbexp}->Add(1, 1, 0, 0, 0);
    
    my $static_line_2 = Wx::StaticLine->new($self->{sz_export_outer}->GetStaticBox(), wxID_ANY);
    $self->{sz_sbexp}->Add($static_line_2, 0, 0, 0);
    
    my $static_line_3 = Wx::StaticLine->new($self->{sz_export_outer}->GetStaticBox(), wxID_ANY);
    $self->{sz_sbexp}->Add($static_line_3, 0, 0, 0);
    
    my $label_2 = Wx::StaticText->new($self->{sz_export_outer}->GetStaticBox(), wxID_ANY, _T("Title"));
    $self->{sz_sbexp}->Add($label_2, 0, wxALIGN_CENTER_VERTICAL, 5);
    
    $self->{t_exporttitle} = Wx::TextCtrl->new($self->{sz_export_outer}->GetStaticBox(), wxID_ANY, "");
    $self->{t_exporttitle}->SetToolTip(_T("Specify the title for the songbook."));
    $self->{sz_sbexp}->Add($self->{t_exporttitle}, 0, wxEXPAND, 5);
    
    my $label_4 = Wx::StaticText->new($self->{sz_export_outer}->GetStaticBox(), wxID_ANY, _T("Cover"));
    $self->{sz_sbexp}->Add($label_4, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{fp_cover} = Wx::FilePickerCtrl->new($self->{sz_export_outer}->GetStaticBox(), wxID_ANY, "", "Select file", "Text files (*.txt)|*.txt|All files|*.*", wxDefaultPosition, wxDefaultSize, wxFLP_FILE_MUST_EXIST|wxFLP_OPEN|wxFLP_SMALL|wxFLP_USE_TEXTCTRL);
    $self->{sz_sbexp}->Add($self->{fp_cover}, 0, wxEXPAND, 0);
    
    $self->{sl_rearrange} = Wx::StaticLine->new($self->{sz_export_outer}->GetStaticBox(), wxID_ANY);
    $self->{sz_export_inner}->Add($self->{sl_rearrange}, 0, wxBOTTOM|wxEXPAND|wxRESERVE_SPACE_EVEN_IF_HIDDEN|wxTOP, 5);
    
    $self->{l_rearrange} = Wx::StaticText->new($self->{sz_export_outer}->GetStaticBox(), wxID_ANY, _T("Rearrange file list"));
    $self->{l_rearrange}->Show(0);
    $self->{sz_export_inner}->Add($self->{l_rearrange}, 0, wxEXPAND|wxRESERVE_SPACE_EVEN_IF_HIDDEN, 0);
    
    $self->{w_rearrange} = Wx::RearrangeCtrl->new($self->{sz_export_outer}->GetStaticBox(), wxID_ANY, wxDefaultPosition, wxDefaultSize, [-1, -1, -1], ['one', 'two', 'three']);
    $self->{w_rearrange}->Show(0);
    $self->{sz_export_inner}->Add($self->{w_rearrange}, 999, wxEXPAND|wxRESERVE_SPACE_EVEN_IF_HIDDEN, 0);
    
    $self->{sz_export_inner}->Add(1, 1, 1, wxEXPAND, 0);
    
    my $static_line_1 = Wx::StaticLine->new($self->{sz_export_outer}->GetStaticBox(), wxID_ANY);
    $self->{sz_export_inner}->Add($static_line_1, 0, wxEXPAND|wxTOP, 5);
    
    $self->{sz_sbexp_buttons} = Wx::FlexGridSizer->new(1, 3, 0, 5);
    $self->{sz_export_inner}->Add($self->{sz_sbexp_buttons}, 0, wxEXPAND|wxTOP, 5);
    
    $self->{l_status} = Wx::StaticText->new($self->{sz_export_outer}->GetStaticBox(), wxID_ANY, "");
    $self->{sz_sbexp_buttons}->Add($self->{l_status}, 0, wxALIGN_CENTER_VERTICAL|wxEXPAND, 0);
    
    $self->{b_preview} = Wx::Button->new($self->{sz_export_outer}->GetStaticBox(), wxID_ANY, _T("Preview"));
    $self->{b_preview}->SetDefault();
    $self->{sz_sbexp_buttons}->Add($self->{b_preview}, 0, 0, 5);
    
    $self->{b_msgs} = Wx::Button->new($self->{sz_export_outer}->GetStaticBox(), wxID_ANY, _T("Show Messages"));
    $self->{sz_sbexp_buttons}->Add($self->{b_msgs}, 0, 0, 0);
    
    $self->{sz_sbexp_buttons}->AddGrowableCol(0);
    
    $self->{sz_sbexp}->AddGrowableCol(1);
    
    $self->SetSizer($self->{sz_export_outer});
    $self->{sz_export_outer}->Fit($self);
    
    $self->Layout();
    Wx::Event::EVT_BUTTON($self, $self->{b_preview}->GetId, $self->can('OnPreview'));
    Wx::Event::EVT_BUTTON($self, $self->{b_msgs}->GetId, $self->can('OnShowMessages'));

    # end wxGlade
    return $self;

}


sub OnPreview {
    my ($self, $event) = @_;
    # wxGlade: ChordPro::Wx::SongbookExportPanel_wxg::OnPreview <event_handler>
    warn "Event handler (OnPreview) not implemented";
    $event->Skip;
    # end wxGlade
}


sub OnShowMessages {
    my ($self, $event) = @_;
    # wxGlade: ChordPro::Wx::SongbookExportPanel_wxg::OnShowMessages <event_handler>
    warn "Event handler (OnShowMessages) not implemented";
    $event->Skip;
    # end wxGlade
}


# end of class ChordPro::Wx::SongbookExportPanel_wxg

1;

