# generated by wxGlade 1.1.0b1 on Wed Sep  4 15:28:13 2024
#
# To get wxPerl visit http://www.wxperl.it
#

use Wx qw[:allclasses];
use strict;

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade

package ChordPro::Wx::SongbookExport_wxg;

use Wx qw[:everything];
use base qw(Wx::Dialog);
use strict;

use Wx::Locale gettext => '_T';
sub new {
    my( $self, $parent, $id, $title, $pos, $size, $style, $name ) = @_;
    $parent = undef              unless defined $parent;
    $id     = -1                 unless defined $id;
    $title  = ""                 unless defined $title;
    $pos    = wxDefaultPosition  unless defined $pos;
    $size   = wxDefaultSize      unless defined $size;
    $name   = ""                 unless defined $name;

    # begin wxGlade: ChordPro::Wx::SongbookExport_wxg::new
    $style = wxDEFAULT_DIALOG_STYLE|wxMAXIMIZE_BOX|wxRESIZE_BORDER
        unless defined $style;

    $self = $self->SUPER::new( $parent, $id, $title, $pos, $size, $style, $name );
    $self->SetSize($self->ConvertDialogSizeToPixels(Wx::Size->new(196, 92)));
    $self->SetTitle(_T("Songbook from Folder"));
    
    $self->{sz_export_outer} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{sz_export_inner} = Wx::BoxSizer->new(wxVERTICAL);
    $self->{sz_export_outer}->Add($self->{sz_export_inner}, 1, wxEXPAND|wxLEFT|wxRIGHT|wxTOP, 5);
    
    $self->{label_3} = Wx::StaticText->new($self, wxID_ANY, _T("Generates and previews a songbook from all ChordPro files in the folder."));
    $self->{label_3}->Wrap(450);
    $self->{sz_export_inner}->Add($self->{label_3}, 0, wxBOTTOM|wxEXPAND, 10);
    
    $self->{sizer_2} = Wx::GridBagSizer->new(5, 5);
    $self->{sz_export_inner}->Add($self->{sizer_2}, 1, wxEXPAND, 5);
    
    $self->{label_1} = Wx::StaticText->new($self, wxID_ANY, _T("Folder"));
    $self->{sizer_2}->Add($self->{label_1}, Wx::GBPosition->new(0, 0), Wx::GBSpan->new(1, 1), wxALIGN_CENTER_VERTICAL, 5);
    
    $self->{sizer_1} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{sizer_2}->Add($self->{sizer_1}, Wx::GBPosition->new(0, 1), Wx::GBSpan->new(1, 1), wxEXPAND, 0);
    
    $self->{t_exportfolder} = Wx::TextCtrl->new($self, wxID_ANY, "");
    $self->{sizer_1}->Add($self->{t_exportfolder}, 1, wxEXPAND, 0);
    
    $self->{b_exportfolder} = Wx::Button->new($self, wxID_ANY, _T("\N{U+2026}"));
    $self->{b_exportfolder}->SetMinSize($self->{b_exportfolder}->ConvertDialogSizeToPixels(Wx::Size->new(18, 13)));
    $self->{sizer_1}->Add($self->{b_exportfolder}, 0, wxFIXED_MINSIZE, 5);
    
    my $label_2 = Wx::StaticText->new($self, wxID_ANY, _T("Title"));
    $self->{sizer_2}->Add($label_2, Wx::GBPosition->new(1, 0), Wx::GBSpan->new(1, 1), wxALIGN_CENTER_VERTICAL, 5);
    
    $self->{t_exporttitle} = Wx::TextCtrl->new($self, wxID_ANY, "");
    $self->{t_exporttitle}->SetToolTip(_T("Specify the title for the songbook."));
    $self->{sizer_2}->Add($self->{t_exporttitle}, Wx::GBPosition->new(1, 1), Wx::GBSpan->new(1, 1), wxEXPAND, 5);
    
    $self->{sz_export_outer}->Add(1, 1, 0, wxEXPAND, 0);
    
    my $static_line_1 = Wx::StaticLine->new($self, wxID_ANY);
    $self->{sz_export_outer}->Add($static_line_1, 0, wxEXPAND|wxTOP, 5);
    
    $self->{sz_sbexp_buttons} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{sz_export_outer}->Add($self->{sz_sbexp_buttons}, 0, wxALL|wxEXPAND, 5);
    
    $self->{sz_sbexp_buttons}->Add(5, 1, 1, wxEXPAND, 0);
    
    $self->{b_cancel} = Wx::Button->new($self, wxID_CANCEL, "");
    $self->{sz_sbexp_buttons}->Add($self->{b_cancel}, 0, 0, 0);
    
    $self->{b_ok} = Wx::Button->new($self, wxID_OK, "");
    $self->{b_ok}->SetDefault();
    $self->{sz_sbexp_buttons}->Add($self->{b_ok}, 0, wxLEFT, 5);
    
    $self->{sizer_2}->AddGrowableCol(1);
    
    $self->SetSizer($self->{sz_export_outer});
    
    $self->Layout();
    Wx::Event::EVT_BUTTON($self, $self->{b_exportfolder}->GetId, $self->can('OnFolderDialog'));
    Wx::Event::EVT_BUTTON($self, $self->{b_cancel}->GetId, $self->can('OnCancel'));
    Wx::Event::EVT_BUTTON($self, $self->{b_ok}->GetId, $self->can('OnAccept'));

    # end wxGlade
    return $self;

}


sub OnFolderDialog {
    my ($self, $event) = @_;
    # wxGlade: ChordPro::Wx::SongbookExport_wxg::OnFolderDialog <event_handler>
    warn "Event handler (OnFolderDialog) not implemented";
    $event->Skip;
    # end wxGlade
}


sub OnCancel {
    my ($self, $event) = @_;
    # wxGlade: ChordPro::Wx::SongbookExport_wxg::OnCancel <event_handler>
    warn "Event handler (OnCancel) not implemented";
    $event->Skip;
    # end wxGlade
}


sub OnAccept {
    my ($self, $event) = @_;
    # wxGlade: ChordPro::Wx::SongbookExport_wxg::OnAccept <event_handler>
    warn "Event handler (OnAccept) not implemented";
    $event->Skip;
    # end wxGlade
}


# end of class ChordPro::Wx::SongbookExport_wxg

1;

